dependencies:
  bme280:
    url: github.com/toitware/bme280-driver
    version: ^1.0.0
  pixel_display:
    url: github.com/toitware/toit-pixel-display
    version: ^1.4.0
  ssd1306:
    url: github.com/toitware/toit-ssd1306
    version: ^1.0.1
